### ISSUE TITLE
State in HA aren't updated while another device change setting on it

### ISSUE THREAD

**Issue by simtreti** [cmroche/greeclimate#102]
Hi,

I have this symptom that happen when i'm using Alexa to send command to my Gree Heat Pump unit, the state aren't updated on HA like it was in the past. The state remain on last one that have been sent from HA previously. If I reload the integration the state is updated succefully though.

Do you need some log ?

**Comment by raadms** [comment]
Hi, @simtreti  

actually I am facing the same exat issue that I noticed it recently where the Gree AC state is not updated on HA. So, if I turned on the AC via Gree remote control home assistant will report that the AC still off and vise versa. Hope this issue get resolved soon. thank you.

**Comment by bem13** [comment]
I also have this issue since Home Assistant 2024.9.1. I can control the AC fine, but the state isn't updated if I use the remote. I see this error in the logs when I send any command through the UI, don't know if it's relevant:
```
homeassistant  | 2024-09-17 10:12:02.498 ERROR (MainThread) [greeclimate.network] Error while handling packet
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/local/lib/python3.12/site-packages/greeclimate/network.py", line 235, in packet_received
homeassistant  |     param = params.get(resp, lambda o, a: (o, a))(obj, addr)
homeassistant  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/local/lib/python3.12/site-packages/greeclimate/network.py", line 225, in <lambda>
homeassistant  |     Response.RESULT.value: lambda o, a: [dict(zip(o["pack"]["opt"], o["pack"]["val"]))],
homeassistant  |                                                                     ~~~~~~~~~^^^^^^^
homeassistant  | KeyError: 'val'
```
