### ISSUE TITLE
daily error from gree integration 

### ISSUE THREAD

**Issue by tammeryousef1006** [cmroche/greeclimate#105]
2024-08-31 23:21:08.255 ERROR (MainThread) [greeclimate.network] Error while handling packet
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/greeclimate/network.py", line 235, in packet_received
param = params.get(resp, lambda o, a: (o, a))(obj, addr)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/greeclimate/network.py", line 225, in <lambda>
Response.RESULT.value: lambda o, a: [dict(zip(o["pack"]["opt"], o["pack"]["val"]))],
~~~~~~~~~^^^^^^^
KeyError: 'val'
2024-09-01 07:00:03.949 ERROR (MainThread) [greeclimate.network] Error while handling packet
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/greeclimate/network.py", line 235, in packet_received
param = params.get(resp, lambda o, a: (o, a))(obj, addr)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/greeclimate/network.py", line 225, in <lambda>
Response.RESULT.value: lambda o, a: [dict(zip(o["pack"]["opt"], o["pack"]["val"]))],
~~~~~~~~~^^^^^^^
KeyError: 'val'

**Comment by dioni-dev** [comment]
I am having the same issue. How to fix it ? I would like to fixed it
