### ISSUE TITLE
HA 117 problems

### ISSUE THREAD

**Issue by DarkPark** [cmroche/greeclimate#12]
Just tried new integration Gree in HA 117.
It was very easy to setup and it found my AC immediately without any problems.
But after some restarts new entities became unavailable.
There are some errors in the log:

```
2020-10-29 00:11:46 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Gree Climate for gree
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 234, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/gree/__init__.py", line 28, in async_setup_entry
    for device_info in await DeviceHelper.find_devices():
  File "/usr/src/homeassistant/homeassistant/components/gree/bridge.py", line 31, in find_devices
    return await Discovery.search_devices()
  File "/usr/local/lib/python3.8/site-packages/greeclimate/discovery.py", line 27, in search_devices
    results = await nethelper.search_devices()
  File "/usr/local/lib/python3.8/site-packages/greeclimate/network.py", line 253, in search_devices
    results = task.result()
  File "/usr/local/lib/python3.8/site-packages/greeclimate/network.py", line 214, in search_on_interface
    while start_ts + timeout > time.time() or await stream.recv_ready():
  File "/usr/local/lib/python3.8/site-packages/greeclimate/network.py", line 127, in recv_ready
    return not await self._recvq.empty()
TypeError: object bool can't be used in 'await' expression
```

The problem is not persistent. After some reboots new entities restored.
It would be nice to make it work all the time without many reboots.

**Comment by DarkPark** [comment]
One more moment - during the night I got a huge amount of such logs:

```
2020-10-29 09:57:57 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.1eb9e391 is taking over 10 seconds
2020-10-29 09:58:57 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.1eb9e391 is taking over 10 seconds
2020-10-29 09:59:57 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.1eb9e391 is taking over 10 seconds
2020-10-29 10:00:57 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.1eb9e391 is taking over 10 seconds
2020-10-29 10:01:57 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.1eb9e391 is taking over 10 seconds
2020-10-29 10:02:57 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.1eb9e391 is taking over 10 seconds
2020-10-29 10:03:57 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.1eb9e391 is taking over 10 seconds
2020-10-29 10:04:57 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.1eb9e391 is taking over 10 seconds
```

I have 4 AC devices (one Gree model). About 95% logs are about climate.1eb9e391 and the rest - about climate.1eb9e3f9.
Another 2 AC just work.

**Comment by cmroche** [comment]
@DarkPark  Thanks for the report, I'll look into it soon.
